### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by VincentLa14** [apache/incubator-superset#3681]
Make sure these boxes are checked before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset-0.20.4

### Expected results
Default dashboards to display

### Actual results
I get "[Errno 5] Input/output error" on all slices. For example, see attachment
<img width="1438" alt="screen shot 2017-10-16 at 3 51 17 pm" src="https://user-images.githubusercontent.com/14893645/31638738-0c60f720-b28a-11e7-954e-d90b8c6504b2.png">

### Steps to reproduce
Ran steps to install `superset` here: https://superset.incubator.apache.org/installation.html

When I go into the slice, the stacktrace I get is
```
Traceback (most recent call last):
  File "/Users/VincentLa/venv/superset-demo/lib/python3.5/site-packages/superset/viz.py", line 273, in get_payload
    try:
  File "/Users/VincentLa/venv/superset-demo/lib/python3.5/site-packages/superset/viz.py", line 97, in get_df
    self.results = self.datasource.query(query_obj)
  File "/Users/VincentLa/venv/superset-demo/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 563, in query
    sql = self.get_query_str(query_obj)
  File "/Users/VincentLa/venv/superset-demo/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 324, in get_query_str
    qry = self.get_sqla_query(**query_obj)
  File "/Users/VincentLa/venv/superset-demo/lib/python3.5/site-packages/superset/connectors/sqla/models.py", line 520, in get_sqla_query
    print('-='*20)
OSError: [Errno 5] Input/output error
```

See the following screenshot from "Birth in France by department in 2016"

<img width="1432" alt="screen shot 2017-10-16 at 3 53 37 pm" src="https://user-images.githubusercontent.com/14893645/31638779-3da4a3fe-b28a-11e7-93c8-68785d0f62fe.png">

**Comment by Coder-Chandler** [comment]
oh! god! I got that error just now!how to fix it?

**Comment by kangjin2014** [comment]
me too. who could help?

**Comment by Coder-Chandler** [comment]
The problem was solved, it was caused by the source code in the 520 line of
the models.py

kangjin2014 <notifications@github.com>于2017年10月23日 周一23:38写道：

**Comment by Coder-Chandler** [comment]
You should delete 520 ,521,522 rows of data from models.py

夏鹏霄 <ysiwgtus@gmail.com>于2017年10月24日 周二18:18写道：

**Comment by VincentLa14** [comment]
Hmm.. I'm still getting this error. Any help?

**Comment by kangjin2014** [comment]
i restarted my mac and superset. and error gone.

**Comment by VincentLa14** [comment]
I just did that as well and the error is still there. Should I uninstall superset and re-install on an older version? maybe 0.20.0?

**Comment by kangjin2014** [comment]
@VincentLa14 i don't know how the error gone in my computer. i was almost trying to run the superset on another mac.

What I did includes
- #build and configure a new detabase connection in superset, eg. 'local'
- #restart mac
- #run following shell commands: 
- superset init
- superset db
- superset runserver

if these couldn't help...then you have to figure out your own way.

**Comment by Coder-Chandler** [comment]
1.did you deleted that code from models.py??
On your computer, probably on this path, you can definitely find it
/Users/chandler/anaconda/envs/superset/lib/python3.6/site-packages/superset/connectors/sqla/models.py
then delete 520,521,522 row of code from models.py

2.if that still not working,Hmm...is there any packages failed during installation?
maby you should check the packages use pip list or condo list?
maby you can reinstall superset.
@VincentLa14

**Comment by VincentLa14** [comment]
I ended up restarting me computer and the issue seemed to have fixed itself..

**Comment by harshita009** [comment]
Reason behind this error?

**Comment by kalimuthu123** [comment]
remove print from it 

because print cannot work with some cloud consoles
