### ISSUE TITLE
Superset Visualizations are timing out after 60 seconds. Want to increase that. How can I implement it?

### ISSUE THREAD

**Issue by swamy16** [apache/incubator-superset#5993]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

**Comment by swamy16** [comment]
Hi All, 
My visualizations are timing out after 60 seconds with an error message "Unexpected error." The query that supports the visualization runs for roughly 2-3 min. This is a complex join query. I want to increase the timeout settings of the visualizations. I tried setting the SUPERSET_WEBSERVER_TIMEOUT to 300 also changed the settings of the gunicorn aswell. @mistercrunch Please let me know how can I do that.

**Comment by swamy16** [comment]
@qin4zhang 
As mentioned in my comment I tried increasing the SUPERSET_WEBSERVER_TIMEOUT to 300 but nothing changed. Also the superset runserver -t didnot work

**Comment by CoryChaplin** [comment]
+1 on this issue, same problem here. Long queries run well in the SQL lab but not in graph views.
According to @abhioncbr on Gitter, il looks like the queries are not run in async mode from the graphs while they are from SQL lab. 
In that case it would be a bug.
The user experience is quite blocking when using tools like Hive that often take more than the default 50 seconds.

**Comment by MaheshYadavalli** [comment]
I'm currently using Superset 0.28.1 and have the same issue.

**Comment by MaheshYadavalli** [comment]
> I'm currently using Superset 0.28.1 and have the same issue.

This can be solved in making changes to file chartAction.js.html

`export <span class="fstat-no" title="function not covered" >function runAnnotationQuery(annotation, <span class="cstat-no" title="statement not covered" >timeout = 60, <span class="cstat-no" title="statement not covered" >formData = null, <span class="cstat-no" title="statement not covered" >key) {</span></span></span></span>
`

**Comment by mistercrunch** [comment]
You can increase the timeout, but ultimately the "explore view" and dashboard view are meant to be somewhat interactive and the "less than a few minutes" time frame is ok for those use cases. If the query takes more than that, say 5-15 minutes, it's pretty clear that it's either too big of a workload, or simply the wrong database engine to power the dashboard. For the Hive use-case, it'd be reasonable perhaps use Hive in a data pipeline to prepare/summarize the data further and load it in a more interactive database, or use Presto. The timeout setup, from an administrative standpoint, prevents users from shooting themselves in the foot.

You'll have to make sure any proxy or load balancer in front of Superset (if any) has longer timeouts setup than Superset itself. Typically web requests are expected to timeout in the 30-120 seconds time frame.

**Comment by mistercrunch** [comment]
@CoryChaplin the `<Loading size={}>` refers to the image size of the loading spinner, totally unrelated.

**Comment by jonberthet** [comment]
Has there been any new developments resolving the 'unexpected error' when a query runtime runs for too long?

**Comment by jackyq2015** [comment]
IMHO, most of the real world query for analytics will be running 60 sec+. can can the cap even exists?

**Comment by saurabh1-singh** [comment]
@swamy16 did you find how to extend the timeout?

**Comment by amitNielsen** [comment]
SUPERSET_WEBSERVER_TIMEOUT =300 works for me

**Comment by imamaigein99** [comment]
I increased SUPERSET_WEBSERVER_TIMEOUT to 300 and i am still getting the below Error. 

[](https://superset.apache.org/docs/miscellaneous/issue-codes#issue-1000)[](https://superset.apache.org/docs/miscellaneous/issue-codes#issue-1001)We’re having trouble loading this visualization. Queries are set to timeout after 60 seconds.


This may be triggered by:
Issue 1000 - The dataset is too large to query. 
Issue 1001 - The database is under an unusual load.

**Comment by moksh-enf** [comment]
In addition, has anyone deployed superset on docker? I would like to increase the timeout there as well.
Thanks!

**Comment by aastafiev** [comment]
setting SUPERSET_WEBSERVER_TIMEOUT won't work

**Comment by ShashankSetty-ByjusAcc** [comment]
any updates on this? did anyone manage to fix it?

**Comment by LeoDiep** [comment]
+1 here

**Comment by moksh-enf** [comment]
You add `SUPERSET_WEBSERVER_TIMEOUT=300` in the .env and .env-non-dev files for docker

**Comment by LeoDiep** [comment]
Here is what I did to solve did on Superset v2.1 docker-compose
Step1: SSH to VM and cd to folder superset docker .../superset/docker/pythonpath_dev/superset_config.py
Add this config into superset_config.py :  SUPERSET_WEBSERVER_TIMEOUT = int(timedelta(minutes=5).total_seconds())

Step2: cd to .../superset/docker and download file **_run-server.sh_** and edit as follow:
--timeout ${GUNICORN_TIMEOUT:-300} \	
Then upload replace original file and restart system.

**Comment by asayeb** [comment]
I have slightly different but i believe in the same category issue. I have set the following values:
    SUPERSET_WEBSERVER_TIMEOUT = 120
    SQLLAB_TIMEOUT = 120
under configOverrides extend_timeout. However after hitting 59 seconds the query editor shows `Database Error, Unknown Error`. I just realized refreshing the page will show that the query is still running and it goes beyond 120 seconds. This could be because of default 6 hours from async query running by celery (but not sure).
I am running superset 2.0.1
anyone having this issue?!

Thanks

**Comment by hxy317** [comment]
> 以下是我在 Superset v2.1 docker-compose 上解决此错误的方法 ： SSH 到 VM 并 cd 到文件夹 superset docker .../superset/docker/pythonpath_dev/superset_config.py 将此 配置添加到 superset_config.py 中： SUPERSET_WEBSERVER_TIMEOUT = int(timedelta(分钟=5).total_seconds())
> 
> Step2: cd 到 .../superset/docker 并下载文件**_run-server.sh_**并编辑如下： --timeout ${GUNICORN_TIMEOUT:-300} \ 然后上传替换原始文件并重新启动系统。

if version is 1.x you will not find run-server.sh try edit .../superset/docker/docker-entrypoint.sh

**Comment by LeoDiep** [comment]
> > 以下是我在 Superset v2.1 docker-compose 上解决此错误的方法 ： SSH 到 VM 并 cd 到文件夹 superset docker .../superset/docker/pythonpath_dev/superset_config.py 将此 配置添加到 superset_config.py 中： SUPERSET_WEBSERVER_TIMEOUT = int(timedelta(分钟=5).total_seconds())
> > Step2: cd 到 .../superset/docker 并下载文件**_run-server.sh_**并编辑如下： --timeout ${GUNICORN_TIMEOUT:-300} \ 然后上传替换原始文件并重新启动系统。
> 
> if version is 1.x you will not find run-server.sh try edit .../superset/docker/docker-entrypoint.sh

I was using docker version 2.5 and actually my reply above didn't work. edit  /superset/docker/run-server.sh  won't work. I had to go inside the container of superset_app and modified it as follow

sudo docker exec -it -u root superset_cache bash					(access Superset cache container as root user)
vi /usr/bin/run-server.sh

SERVER_WORKER_AMOUNT:-6									(Based on the specs of the instant running Superset)
SERVER_THREAD_AMOUNT:-30
GUNICONR_TIMEOUT:-300

**Comment by dothangTH** [comment]
I bumped into the same issue. I'm running v2.1 on k8s. Tried fixing as @LeoDiep mentioned above but didn't work. The visualisation still got timeout after 60 seconds. As I inspected the k8s pod running the webserver, `--timeout` option in the `gunicorn` execution command was set to 300 as I expected. 

Anyone can help me with this? TY in advance!

**Comment by LeoDiep** [comment]
> I bumped into the same issue. I'm running v2.1 on k8s. Tried fixing as @LeoDiep mentioned above but didn't work. The visualisation still got timeout after 60 seconds. As I inspected the k8s pod running the webserver, `--timeout` option in the `gunicorn` execution command was set to 300 as I expected.
> 
> Anyone can help me with this? TY in advance!

Hi, did you edit the superset_config.py : SUPERSET_WEBSERVER_TIMEOUT = int(timedelta(minutes=5).total_seconds())

**Comment by moksh-enf** [comment]
> I bumped into the same issue. I'm running v2.1 on k8s. Tried fixing as @LeoDiep mentioned above but didn't work. The visualisation still got timeout after 60 seconds. As I inspected the k8s pod running the webserver, `--timeout` option in the `gunicorn` execution command was set to 300 as I expected.
> 
> Anyone can help me with this? TY in advance!

You could also check the `.env` and `.env-non-dev` files and update the `SUPERSET_WEBSERVER_TIMEOUT` flag there

**Comment by aks1981** [comment]
Hi 

> > I bumped into the same issue. I'm running v2.1 on k8s. Tried fixing as @LeoDiep mentioned above but didn't work. The visualisation still got timeout after 60 seconds. As I inspected the k8s pod running the webserver, `--timeout` option in the `gunicorn` execution command was set to 300 as I expected.
> > Anyone can help me with this? TY in advance!
> 
> Hi, did you edit the superset_config.py : SUPERSET_WEBSERVER_TIMEOUT = int(timedelta(minutes=5).total_seconds())

Is this resolved for you? We did the same change still same issue for Superset installed version 3.0.1

**Comment by aks1981** [comment]
I also bumped same issue in production. My report query is tacking more than 5 minutes and leading to timeout on dashboard. Please help me out if anyone has fix this issue.
Superset version - 3.1.1

<img width="609" alt="Screenshot 2024-04-29 at 3 22 27 PM" src="https://github.com/apache/superset/assets/24263770/b0d77361-c158-4df1-b756-8e02e2d51b95">

**Comment by moksh-enf** [comment]
> I also bumped same issue in production. My report query is tacking more than 5 minutes and leading to timeout on dashboard. Please help me out if anyone has fix this issue. Superset version - 3.1.1
> 
> <img alt="Screenshot 2024-04-29 at 3 22 27 PM" width="609" src="https://private-user-images.githubusercontent.com/24263770/326407584-b0d77361-c158-4df1-b756-8e02e2d51b95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDQ5NTYsIm5iZiI6MTcxNDQwNDY1NiwicGF0aCI6Ii8yNDI2Mzc3MC8zMjY0MDc1ODQtYjBkNzczNjEtYzE1OC00ZGYxLWI3NTYtOGUwMmUyZDUxYjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE1MzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDFhNGRiZmQxYzk3ZjY5NWYwMGQ0NTJiN2IwYTY0ZjdjYTNhZTg4MjA2MGIyZjI0OGQ0NjNmN2U3NTUyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMMOme16hz1Nqk3x0OwbwnXZ-xo0ivYEow2CfLIPA5Q">

Did you check the .env and .env-non-dev files and update the `SUPERSET_WEBSERVER_TIMEOUT` flag there?

**Comment by aks1981** [comment]
instead of SUPERSET_WEBSERVER_TIMEOUT = int(timedelta(minutes=5).total_seconds())
Changed with fixed value as below. Its working fine. 
 SUPERSET_WEBSERVER_TIMEOUT = 1200

**Comment by nehagoushal-cs** [comment]
I have set SUPERSET_WEBSERVER_TIMEOUT = 21600 (6 hours) which I assume should be enough.
But I am still getting '504 Gateway Timeout' error on all my charts after 60 seconds.
<img width="648" alt="Screenshot 2025-01-09 at 9 26 27 AM" src="https://github.com/user-attachments/assets/2f716843-3bc5-4fe9-ba66-f529b5e4f62a" />
Anything else that I can try to fix this?

**Comment by Kolliderrr** [comment]
> I have set SUPERSET_WEBSERVER_TIMEOUT = 21600 (6 hours) which I assume should be enough. But I am still getting '504 Gateway Timeout' error on all my charts after 60 seconds. <img alt="Screenshot 2025-01-09 at 9 26 27 AM" width="648" src="https://private-user-images.githubusercontent.com/188394719/401638207-2f716843-3bc5-4fe9-ba66-f529b5e4f62a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkyNTk5MjAsIm5iZiI6MTczOTI1OTYyMCwicGF0aCI6Ii8xODgzOTQ3MTkvNDAxNjM4MjA3LTJmNzE2ODQzLTNiYzUtNGZlOS1iYTY2LWY1MjliNWU0ZjYyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMVQwNzQwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjY2NDUzNzNjMGRjYWVhNTlkNzg3MzkzN2UzNGQ0MTM5ZDUxYzA2MTdlM2FhMjRkMjljNmY2NDlkZjE4ZTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OBglEQXN2UxietglVFGGGLEpTpJqlbJU6yf_iDYy4z0"> Anything else that I can try to fix this?

Another workaround is to increase conn.timeout to DB using SQLAlchemy Engine params:

![Image](https://github.com/user-attachments/assets/b5a5574e-df13-45f4-b4bf-e68c61fafd9f)

**Comment by praveenhalian** [comment]
I hope this email finds you well.
I am reaching out for assistance with an ongoing issue we are facing with our Superset deployment. We have configured various timeout settings for SQL Lab, Gunicorn, and other related parameters, but we continue to encounter a 504 Gateway Timeout (60000ms) error when performing queries through the Superset portal.
Issue Details:
Error: 504 Gateway Timeout (60000ms)
Superset Version: [insert version here]
Timeout Configuration: We have updated the following timeout values in the superset_config.py:
SQLLAB_TIMEOUT = 1800
SQLLAB_ASYNC_TIME_LIMIT_SEC = 1800
SUPERSET_WEBSERVER_TIMEOUT = 1800
SUPERSET_SQLALCHEMY_TIMEOUT = 1800
GUNICORN_TIMEOUT = 1800
Despite setting these values, the portal is still enforcing a 60-second timeout limit.
Troubleshooting Steps Taken:
Cleared Superset cache using superset init.
Restarted the Superset deployment after changes.
Ensured the environment variable FRONTEND_TIMEOUT was set correctly.
Cleared browser cache and tested in incognito mode.
Verified Nginx and Ingress timeout settings.
Checked logs for any errors related to timeouts.
Despite these steps, the timeout issue persists, and SQL queries are still getting cut off after 60 seconds.
Request:
I would appreciate your assistance in:
Confirming whether there are any additional configuration settings or steps needed to apply a 30-minute timeout effectively.
Identifying if there are any issues with how the timeout settings are being processed within the Superset environment.
Please let me know if you require any additional information or logs from my side to help diagnose and resolve this issue.
Thank you for your assistance.
@Kolliderrr 













Message Ghazi Triki

**Comment by Kolliderrr** [comment]
> I hope this email finds you well. I am reaching out for assistance with an ongoing issue we are facing with our Superset deployment. We have configured various timeout settings for SQL Lab, Gunicorn, and other related parameters, but we continue to encounter a 504 Gateway Timeout (60000ms) error when performing queries through the Superset portal. Issue Details: Error: 504 Gateway Timeout (60000ms) Superset Version: [insert version here] Timeout Configuration: We have updated the following timeout values in the superset_config.py: SQLLAB_TIMEOUT = 1800 SQLLAB_ASYNC_TIME_LIMIT_SEC = 1800 SUPERSET_WEBSERVER_TIMEOUT = 1800 SUPERSET_SQLALCHEMY_TIMEOUT = 1800 GUNICORN_TIMEOUT = 1800 Despite setting these values, the portal is still enforcing a 60-second timeout limit. Troubleshooting Steps Taken: Cleared Superset cache using superset init. Restarted the Superset deployment after changes. Ensured the environment variable FRONTEND_TIMEOUT was set correctly. Cleared browser cache and tested in incognito mode. Verified Nginx and Ingress timeout settings. Checked logs for any errors related to timeouts. Despite these steps, the timeout issue persists, and SQL queries are still getting cut off after 60 seconds. Request: I would appreciate your assistance in: Confirming whether there are any additional configuration settings or steps needed to apply a 30-minute timeout effectively. Identifying if there are any issues with how the timeout settings are being processed within the Superset environment. Please let me know if you require any additional information or logs from my side to help diagnose and resolve this issue. Thank you for your assistance. [@Kolliderrr](https://github.com/Kolliderrr)
> 
> Message Ghazi Triki

Can you send me an example of nginx-config?
What were the steps you followed through customizing variables? Mb restart superset - superset init?

**Comment by praveenhalian** [comment]
#
apiVersion: v1
data:
  allow-snippet-annotations: "true"
  enable-underscores-in-headers: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"allow-snippet-annotations":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":
"controller","app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ingress-nginx","app.kubernetes.io/v
ersion":"1.1.0","helm.sh/chart":"ingress-nginx-4.0.10"},"name":"ingress-nginx-controller","namespace":"ingress-nginx"}}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  creationTimestamp: "2023-12-15T07:46:47Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.1.0   @Kolliderrr

**Comment by praveenhalian** [comment]
Fixed the issue

`Enable Asynchronous Query Execution:

Go to the Database Connection page in Superset.

Navigate to the Advanced tab.

Click on the Performance tab.

Enable the Asynchronous Query Execution option.

Install Required Dependencies:

Install the cx_Oracle Python package:

bash
Copy
pip install cx_Oracle
Install the libaio1 library (required for Oracle Instant Client):

bash
Copy
sudo apt install libaio1
Create Persistent Volumes (PV) and Persistent Volume Claims (PVC):

Create the necessary PV and PVC for Oracle client and wallet storage.

Edit Superset and Superset Worker YAML Files:

Add the following environment variables and volume mounts to both the superset and superset-worker YAML files:

yaml
Copy
env:
  - name: SUPERSET_PORT
    value: "8088"
  - name: LD_LIBRARY_PATH
    value: /opt/oracle/instantclient
  - name: ORACLE_HOME
    value: /opt/oracle/instantclient
  - name: TNS_ADMIN
    value: /opt/oracle/instantclient/network/admin

volumeMounts:
  - mountPath: /app/pythonpath
    name: superset-config
    readOnly: true
  - mountPath: /opt/oracle/instantclient
    name: oracle-client
  - mountPath: /opt/wallet
    name: oracle-wallet
  - mountPath: /opt/oracle/instantclient/network/admin
    name: tnsnames-config

volumes:
  - name: superset-config
    secret:
      defaultMode: 420
      secretName: superset-config
  - name: oracle-client
    persistentVolumeClaim:
      claimName: oracle-client-pvc
  - name: oracle-wallet
    secret:
      defaultMode: 420
      secretName: oracle-wallet
  - name: tnsnames-config
    configMap:
      defaultMode: 420
      name: tnsnames-config
Deploy the Changes:

Apply the updated YAML files to your Kubernetes cluster to deploy the changes.

Explanation of Key Steps:
Asynchronous Query Execution: Improves performance by allowing queries to run asynchronously.

cx_Oracle and libaio1: Required for Oracle database connectivity.

PV and PVC: Ensures persistent storage for Oracle client and wallet files.

Environment Variables and Volume Mounts: Configures the necessary paths and settings for Oracle connectivity in Superset.


`

**Comment by yalefresne** [comment]
I faced a similar problem.

I was able to resolve it by setting `SCREENSHOT_LOCATE_WAIT` and `SCREENSHOT_LOAD_WAIT` variables on `superset_config.py`  like this:
```
SCREENSHOT_LOCATE_WAIT = int(timedelta(seconds=120).total_seconds())
SCREENSHOT_LOAD_WAIT = int(timedelta(seconds=120).total_seconds())
```
This fixed the issue for me, with vizualization which contain png screenshot made via selenium.  
Hope this helps!

**Comment by praveenhalian** [comment]
Public

Thank you , issue got resolved, enabled the celery worker node

Get Outlook for iOS<https://aka.ms/o0ukef>


Public

________________________________

**Comment by gpchandran** [comment]
> Public
> 
> Thank you , issue got resolved, enabled the celery worker node
> 
> Get Outlook for iOS<https://aka.ms/o0ukef>
> 
> 
> Public
> […](#)
> 
> ________________________________
> From: yalefresne ***@***.***>
> Sent: Friday, February 14, 2025 8:30:24 PM
> To: apache/superset ***@***.***>
> Cc: Praveen Prakasan (Secondee) ***@***.***>; Comment ***@***.***>
> Subject: Re: [apache/superset] Superset Visualizations are timing out after 60 seconds. Want to increase that. How can I implement it? ([#5993](https://github.com/apache/superset/issues/5993))
> 
> You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>
> 
> CAUTION: This email originated from outside of NEOM. Please do not click links or open attachments unless you recognize the sender and know the content is safe.
> 
> 
> I faced a similar problem.
> 
> I was able to resolve it by setting SCREENSHOT_LOCATE_WAIT and SCREENSHOT_LOAD_WAIT variables on superset_config.py like this:
> 
> SCREENSHOT_LOCATE_WAIT = int(timedelta(seconds=120).total_seconds())
> SCREENSHOT_LOAD_WAIT = int(timedelta(seconds=120).total_seconds())
> 
> 
> This fixed the issue for me, with vizualization which contain png screenshot made via selenium.
> Hope this helps!
> 
> —
> Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=e81b8c9f-8bc40336-e81ccfe8-74fe486dcd97-2125920ed2a4026c&q=1&e=6fb29e34-d2f1-4a1f-af96-265a521f8710&u=https%3A%2F%2Fgithub.com%2Fapache%2Fsuperset%2Fissues%2F5993%23issuecomment-2659775237>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=3c328dab-5fed0202-3c35cedc-74fe486dcd97-6e32f776d18178a8&q=1&e=6fb29e34-d2f1-4a1f-af96-265a521f8710&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA4JZGBJG4ZV35TF5VI35YDD2PYK2BAVCNFSM6AAAAABUULJFQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNJZG43TKMRTG4>.
> You are receiving this because you commented.Message ID: ***@***.***>
> 
> [yalefresne]yalefresne left a comment ([apache/superset#5993](https://github.com/apache/superset/issues/5993))<https://protect2.fireeye.com/v1/url?k=f367e3bd-90b86c14-f360a0ca-74fe486dcd97-f23e7e82d79b815c&q=1&e=6fb29e34-d2f1-4a1f-af96-265a521f8710&u=https%3A%2F%2Fgithub.com%2Fapache%2Fsuperset%2Fissues%2F5993%23issuecomment-2659775237>
> 
> I faced a similar problem.
> 
> I was able to resolve it by setting SCREENSHOT_LOCATE_WAIT and SCREENSHOT_LOAD_WAIT variables on superset_config.py like this:
> 
> SCREENSHOT_LOCATE_WAIT = int(timedelta(seconds=120).total_seconds())
> SCREENSHOT_LOAD_WAIT = int(timedelta(seconds=120).total_seconds())
> 
> 
> This fixed the issue for me, with vizualization which contain png screenshot made via selenium.
> Hope this helps!
> 
> —
> Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=7546d9a1-16995608-75419ad6-74fe486dcd97-14790a7db02ef2ec&q=1&e=6fb29e34-d2f1-4a1f-af96-265a521f8710&u=https%3A%2F%2Fgithub.com%2Fapache%2Fsuperset%2Fissues%2F5993%23issuecomment-2659775237>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=8c54be45-ef8b31ec-8c53fd32-74fe486dcd97-f3e5165be46a68ea&q=1&e=6fb29e34-d2f1-4a1f-af96-265a521f8710&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA4JZGBJG4ZV35TF5VI35YDD2PYK2BAVCNFSM6AAAAABUULJFQOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMNJZG43TKMRTG4>.
> You are receiving this because you commented.Message ID: ***@***.***>

Hi @praveenhalian ,

Thanks after enabling **Asynchronous query execution** in Database connection setting , SQLLab Gateway time-out issue fixed for me. But **still getting Time-out Chart Level**, how to fix this issue? your help highly appreciated!

**Comment by gpchandran** [comment]
Hi @praveenhalian  @jackyq2015  @sadpandajoe  @michael-s-molina  or anyone - please help if you have ideas

Enabling Asynchronous query execution in the Database connection settings resolved the SQLLab Gateway time-out issue for me. However, I'm still encountering a Chart Level Gateway time-out after 60 seconds. Could you please assist me in resolving this issue? Your help would be greatly appreciated!

Here are my Superset config settings

    # Timeout settings
    SQLLAB_TIMEOUT = 300
    SQLLAB_ASYNC_TIME_LIMIT_SEC = 600
    SUPERSET_WEBSERVER_TIMEOUT = 300
    SUPERSET_SQLALCHEMY_TIMEOUT = 600
    GUNICORN_TIMEOUT = 300
    SCREENSHOT_LOCATE_WAIT = 300
    SCREENSHOT_LOAD_WAIT = 300

**Comment by rishika-ushur** [comment]
I'm also getting the same issue. ANy resolutions for this ? 


I also have an issue, i am getting once in a while 502 bad gateway errors when opening many tabs of superset dashboards (so they load all together).
the issue is that it happens immediately because of the load (i do have enough resources) and not because the timeout is passed.
also after one refresh it is going back to normal and i am able to see the dashboards without any errors.
tried to scale the superset-node to 5 but it still does not work.
also tried to set gunicorn keep-alive and threads to 60 but none of them helped
what else can I do?
Thanks
