### ISSUE TITLE
Filter box disappear after date filter applied

### ISSUE THREAD

**Issue by famasya** [apache/incubator-superset#6165]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.28.1

### Expected results

Filter box stays after date filter applied.

### Actual results

Got error message: Uncaught TypeError: Cannot read property 'map' of undefined. Filter box also disappear after date filter applied. However, charts successfully filtered within date range.

### Steps to reproduce

1. Create dashboard
2. Add filter to dashboard
3. Apply date filter

**Comment by famasya** [comment]
Looks like similar bug was found in #3649 with different case

**Comment by UFSMEPS** [comment]
Same issue here after the last release update!

**Comment by opus-42** [comment]
Same Issue here

**Comment by Jemteddy** [comment]
Same for me.

**Comment by mistercrunch** [comment]
This issue is so weird. Only some laptops/browsers seem to be affected. For instance I cannot reproduce it on my browser but people sitting next to me can, with the exact same version of chrome.

**Comment by Jemteddy** [comment]
I get the error everytime and ask some of my colleagues to try and they got the same error. However, if I try on Firefox (I usually use Chrome), the error is 'TypeError: "t is undefined"' (on Chrome, on the same dashboard, I also have "Uncaught TypeError: Cannot read property 'map' of undefined.") .
Moreover on some dashboards the filter box shows up and disappear when I use it, on others I have the error straight away.

**Comment by yuezhiling2** [comment]
Same error with Firefox. The error is "[3016]/E</<.value</</<@http://**/static/assets/dist/filter_box.885b5b9fd31f4d3caa48.chunk.js:2:364709
[3016]/E</<.value</<@http://**/static/assets/dist/filter_box.885b5b9fd31f4d3caa48.chunk.js:2:364605
[3016]/E</<.value</<@http://**/static/assets/dist/filter_box.885b5b9fd31f4d3caa48.chunk.js:2:365980
Qi@http://**/static/assets/dist/vendors-major.4f5a17619ab655ae0e0c.chunk.js:2:1384795
Xi@http://**/static/assets/dist/vendors-major.4f5a17619ab655ae0e0c.chunk.js:2:1384639
to@http://**/static/assets/dist/vendors-major.4f5a17619ab655ae0e0c.chunk.js:2:1387239
Ro@http://**/static/assets/dist/vendors-major.4f5a17619ab655ae0e0c.chunk.js:2:1401252
No@http://**/static/assets/dist/vendors-major.4f5a17619ab655ae0e0c.chunk.js:2:1401598"

**Comment by mistercrunch** [comment]
We had this issue in production at Lyft and I fixed it with this patch. From what I understand the bug should not exist in master or in `0.28.x`:
https://github.com/lyft/incubator-superset/commit/57410671fb90aa86433274eb6dd644b134b92dbe

**Comment by Jemteddy** [comment]
The issue is with version `0.28.1`, do you mean it's fixed on next versions ? I tried to reproduce your fix  in `superset/static/assets/coverage/lcov-report/src/visualizations/filter_box.jsx.html` but the issue is still there.

**Comment by Jemteddy** [comment]
Thanks !

**Comment by dmigo** [comment]
Is there a quick fix for this one? Something like 'add X to the slice's properties?'

**Comment by yogeshmhaskule** [comment]
I am facing the same issue. Also using the latest version of superset 0.28.1. I tried it on Chrome and Safari browsers.

**Comment by akash-y** [comment]
Facing the same issue still. Tried it on Chrome and Safari browsers as well.

**Comment by returnoftheturk** [comment]
I am also having issues with this with Superset version 0.28.0 and 0.28.1.  0.27.0 does not have the same problem.  In terms of future releases, I haven't been able to get superset running using the Dockerfile, and am relying on pip install superset, so the latest release I can use is 0.28.1.

**Comment by akash-y** [comment]
@abhijitghate

**Comment by nuria** [comment]
+1 to prior comment, we run into this issue with 0.28.1

**Comment by crodrigueza16** [comment]
Same issue @nuria 

@mistercrunch Can you re-open this issue?

**Comment by jgarciaISITECH** [comment]
Same issue @nuria :( 
Is there a quick fix for this one?

**Comment by thda** [comment]
Hi,

is it possible to backport to 0.28, or to give an estimate date for the release of 0.29 ?
It's a severe issue.

Thanks

**Comment by mistercrunch** [comment]
We're currently recommending running `0.29.0rc7` where this issue is fixed. We're held up on releases until we can spend cycles sorting out LICENSE related documentation to comply with the ASF for official releases.

**Comment by coolboi567** [comment]
@mistercrunch how long will it take for `v0.29` to release?

**Comment by agabardo** [comment]
Same issue here..
