### ISSUE TITLE
Error `The CSRF session token is missing` when embed superset in iframe

### ISSUE THREAD

**Issue by YBLS** [apache/incubator-superset#8382]
Error `The CSRF session token is missing` when embed superset in iframe

### Expected results

Embed charts or dashboard in my web page via iframe

Code
``` javascript
<iframe
  width="1600"
  height="800"
  seamless
  frameBorder="0"
  scrolling="no"
  src="http://192.168.11.118:8088/superset/explore/?form_data=%7B%22datasource%22%3A%2212__table%22%2C%22viz_type%22%3A%22deck_path%22%2C%22slice_id%22%3A81%2C%22url_params%22%3A%7B%7D%2C%22granularity_sqla%22%3Anull%2C%22time_grain_sqla%22%3Anull%2C%22time_range%22%3A%22+%3A+%22%2C%22line_column%22%3A%22path_json%22%2C%22line_type%22%3A%22json%22%2C%22row_limit%22%3A5000%2C%22filter_nulls%22%3Atrue%2C%22adhoc_filters%22%3A%5B%5D%2C%22mapbox_style%22%3A%22mapbox%3A%2F%2Fstyles%2Fmapbox%2Flight-v9%22%2C%22viewport%22%3A%7B%22altitude%22%3A1.5%2C%22bearing%22%3A0%2C%22height%22%3A1094%2C%22latitude%22%3A37.73671752604488%2C%22longitude%22%3A-122.18885402582598%2C%22maxLatitude%22%3A85.05113%2C%22maxPitch%22%3A60%2C%22maxZoom%22%3A20%2C%22minLatitude%22%3A-85.05113%2C%22minPitch%22%3A0%2C%22minZoom%22%3A0%2C%22pitch%22%3A0%2C%22width%22%3A669%2C%22zoom%22%3A9.51847667620428%7D%2C%22color_picker%22%3A%7B%22a%22%3A1%2C%22b%22%3A135%2C%22g%22%3A122%2C%22r%22%3A0%7D%2C%22line_width%22%3A150%2C%22reverse_long_lat%22%3Afalse%2C%22autozoom%22%3Atrue%2C%22js_columns%22%3A%5B%22color%22%5D%2C%22js_data_mutator%22%3A%22data+%3D%3E+data.map%28d+%3D%3E+%28%7B%5Cn++++...d%2C%5Cn++++color%3A+colors.hexToRGB%28d.extraProps.color%29%5Cn%7D%29%29%3B%22%2C%22js_tooltip%22%3A%22%22%2C%22js_onclick_href%22%3A%22%22%7D&standalone=true&height=400"
>
</iframe>
```

##### Access in chrome address bar
Successful access
##### When access my web page via iframe
- Role `admin`
When I login, Receive Error "<h1>Bad Request</h1> <p>The CSRF session token is missing.</p>"
- Role `public`
Receive Error `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>400 Bad Request</title> <h1>Bad Request</h1> <p>The CSRF session token is missing.</p>`

#### How to reproduce the bug

1. Launch Apache Superset in virtualenv `superset run -h 0.0.0.0 -p 8088`
2. Connect the link via iframe into another separate webpage
3. See error

### Environment

(please complete the following information):

- superset version: ` 0.999.0dev  /  master 2019-10-13`
- python version: `3.7.3`
- node.js version: `v10.15.2`
- npm version: `5.8.0`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

config.py setting
`PUBLIC_ROLE_LIKE_GAMMA = True`

**Comment by YBLS** [comment]
I have solved this problem.
`SESSION_COOKIE_SAMESITE = None  # One of [None, 'Lax', 'Strict']`

**Comment by azure31** [comment]
> I have solved this problem.
> `SESSION_COOKIE_SAMESITE = None # One of [None, 'Lax', 'Strict']`

@YBLS : Which file did you update this in? I added it to superset_config.py and it didn't work for me.

**Comment by andrewmusselman** [comment]
Where did you set this? I've installed superset using pip and can't tell where I can set that variable; thanks.

**Comment by YBLS** [comment]
> Where did you set this? I've installed superset using pip and can't tell where I can set that variable; thanks.

set in superset/config.py。This is flask session cookie options

**Comment by lilila** [comment]
In superset 0.36 it is also necessary to set 
`SESSION_COOKIE_HTTPONLY = False` 
to get dashboard working (without CSRF token issue) within iframe

**Comment by Jamesvasanth21** [comment]
It is not working do you guys have any other suggestions??
This is the error I am getting
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>400 Bad Request</title> <h1>Bad Request</h1> <p>The CSRF session token is missing.</p>

**Comment by raoofnaushad** [comment]
> I have solved this problem.
> `SESSION_COOKIE_SAMESITE = None # One of [None, 'Lax', 'Strict']`

Thanks man

**Comment by SaiManojG** [comment]
tried placing those properties in config.py, still getting the same result when using iframe in another domain, but when accessing in the same domain ( ex: localhost ) everything is working just fine.


please help, thanks in advance!

**Comment by trepmag** [comment]
This issue produce quiet some confusion because browsers behaviors aren't aligned...

Actually, what I noticed is the following:
```
SESSION_COOKIE_SAMESITE = "None" # Sufficient for Firefox
SESSION_COOKIE_SECURE = True # Required for Google Chrome (at least from version 84)
```

This above setup is stated is a [IETF proposal: Incrementally Better Cookies](https://tools.ietf.org/html/draft-west-cookie-incrementalism-00) and was ported to my attention in this article: [Cookies and Iframes](https://medium.com/trabe/cookies-and-iframes-f7cca58b3b9e).

More over, note that it appears that Google Chrome in incognito mode will fail!...

**Comment by michalrudko** [comment]
If your Superset is not under https, the following setup worked for me:
```
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False 
SESSION_COOKIE_HTTPONLY = False
```

Superset v.1.0.1, Chrome 89

**Comment by zhugw** [comment]
I use version 1.1.0 
My way is 
```
WTF_CSRF_ENABLED = False
```

**Comment by im-naren** [comment]
how can this issue be solved in a helm deployment??

**Comment by clarabez** [comment]
Also changing "CSRF_ENABLED" to False worked for me:

`CSRF_ENABLED = False`

**Comment by kakoni** [comment]
Please note, its `SESSION_COOKIE_SAMESITE = "None"` not `SESSION_COOKIE_SAMESITE = None`

**Comment by vishaltps** [comment]
I am still getting the same error even after applying all the configurations.

I have tried setting `SESSION_COOKIE_SAMESITE = "None" ` and `SESSION_COOKIE_SAMESITE = None `. I am using HTTPS and I don't want to disable CSRF.
I am getting below error

```
"{\"errors\": [{\"message\": \"400 Bad Request: The CSRF session token is missing.\", \"error_type\": \"GENERIC_BACKEND_ERROR\", \"level\": \"error\", \"extra\": {\"issue_codes\": [{\"code\": 1011, \"message\": \"Issue 1011 - Superset encountered an unexpected error.\"}]}}]}
```

It is working fine when i am trying to call API from Postman. However, in the app, I keep getting the same error. I have also attached `"Referer"=>"https://mydomain/api/v1/security/csrf_token/`.

**Comment by vishaltps** [comment]
I have added complete blog on integration of embed superset dashboard - https://medium.com/p/697da01676af

**Comment by Alvie** [comment]
> I have added complete blog on integration of embed superset dashboard - https://medium.com/@vishalsadriya1224/embedding-apache-superset-dashboards-in-ruby-on-rails-and-react-a-role-level-security-guide-697da01676af

I think disabling CSP, is a somewhat dangerous way of doing it. You should copy across the talisman config in config.py to superset_config.py, but allow frame ancestors from hosts you choose. Or even '*', but disabling talisman altogether and replacing it with custom CORS options is a bit complex and potentially dangerous if you do not know what you're doing.

Anyway, yes, from what I can tell, the issue is from the cookie not being set, so it is good you are including this.

**Comment by Rudneer** [comment]
@Alvie Nope still the same error.
set_cookie = response.headers['set-cookie']
i am using set-cookie from csrf reponse header

**Comment by Alvie** [comment]
> @Alvie Nope still the same error. set_cookie = response.headers['set-cookie'] i am using set-cookie from csrf reponse header My cookie contains 3 params 1 AWSALBTG 2 AWSALBTGCORS 3 session it contains token value, expires and path

For me, the cookie `session` value contains the csrf token and it works.

**Comment by Alvie** [comment]
> @Alvie Nope still the same error. set_cookie = response.headers['set-cookie'] i am using set-cookie from csrf reponse header My cookie contains 3 params 1 AWSALBTG 2 AWSALBTGCORS 3 session it contains token value, expires and path

I don't think the cookie is meant to be a header by the way, it might be an independent parameter.

If you are using python requests, it is something like this:

```py
cookies = {'enwiki_session': '17ab96bd8ffbe8ca58a78657a918558'}

r = requests.post('http://wikipedia.org', cookies=cookies)
```

https://stackoverflow.com/a/7164897

**Comment by Rudneer** [comment]
@Alvie https://github.com/apache/superset/issues/8382#issuecomment-1690197367
in your above comment u mentioned i have to pass set cookie header alongside token.

**Comment by Alvie** [comment]
> @Alvie [#8382 (comment)](https://github.com/apache/superset/issues/8382#issuecomment-1690197367) in your above comment u mentioned i have to pass set cookie header alongside token.

You misunderstood. The server responds with the Set-Cookie header, so your client application should set that cookie. Many libraries don't persist cookies, so this is something you need to do yourself. Whatever the Set-Cookie has the server has responded with e.g. `'session': 'csrf_cookie_value'`, in your cookies in future responses need to have `'session': 'csrf_cookie_value'`

**Comment by spars57** [comment]
I'm still having this issue, the cookie is stored on the browser and is being sent to API but the same error persists. Did anyone find a solution for this?

**Comment by Alvie** [comment]
> I'm still having this issue, the cookie is stored on the browser and is being sent to API but the same error persists. Did anyone find a solution for this?

Can you send an example of your API Request Headers?

**Comment by spars57** [comment]
Here are the print screens of the request that I'm doing:

<img width="1012" alt="image" src="https://github.com/apache/superset/assets/79933117/3556d31b-1eb9-48d1-b6ea-af25081beed0">

<img width="1013" alt="image" src="https://github.com/apache/superset/assets/79933117/69b15deb-5099-4cbb-bdba-f0df1469a261">

<img width="1014" alt="image" src="https://github.com/apache/superset/assets/79933117/3599e34b-e5b7-40d0-9a85-b838b007fd5c">

Even with Authorization, X-CSRF-Token headers and Session Cookie being passed, looks like the error persists

<img width="981" alt="image" src="https://github.com/apache/superset/assets/79933117/576b3dd3-43b1-45d8-a5f6-74490dc60509">

**Comment by spars57** [comment]
"I could be wrong but it looks like there's no cookies being sent in the request. Maybe the cookie from the Set-Cookie response hasn't been applied to the client"

Do you know how I can apply that cookie to the client?

**Comment by spars57** [comment]
Actually adding { credentials: "include" } to fetch() options solved the issue, thanks!

**Comment by Alvie** [comment]
> Actually adding { credentials: "include" } to fetch() options solved the issue, thanks!

You're very welcome! Glad to hear your issue is fixed :)

**Comment by 1sarah** [comment]
your config.py should look like this .................
TALISMAN_ENABLED = False
HTTP_HEADERS={"X-Frame-Options":"ALLOWALL"}
DATA_CACHE_CONFIG = CACHE_CONFIG
ENABLE_PROXY_FIX = True
ENABLE_CORS = True #TO enable cores
WTF_CSRF_ENABLED=False #To enable csrf token
CORS_OPTIONS = {
    "supports_credentials": True,
    "allow_headers": "*",
    "expose_headers": "*",
    "resources": "*",
    "origins": ["*"]
}
This worked for me

**Comment by Alvie** [comment]
> your config.py should look like this ................. TALISMAN_ENABLED = False HTTP_HEADERS={"X-Frame-Options":"ALLOWALL"} DATA_CACHE_CONFIG = CACHE_CONFIG ENABLE_PROXY_FIX = True ENABLE_CORS = True #TO enable cores WTF_CSRF_ENABLED=False #To enable csrf token CORS_OPTIONS = { "supports_credentials": True, "allow_headers": "_", "expose_headers": "_", "resources": "_", "origins": ["_"] } This worked for me

This will work, but it's dangerous to present it as the solution because you disabled many security features in the process.

This will disable CSP, CSRF, and Talisman, and allows CORS from anywhere.
